# Generated by Django 5.0.1 on 2024-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
